kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: windows-machine-config-operator
subjects:
- kind: ServiceAccount
  name: windows-machine-config-operator
roleRef:
  kind: ClusterRole
  name: windows-machine-config-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: windows-machine-config-operator
subjects:
- kind: ServiceAccount
  name: windows-machine-config-operator
roleRef:
  kind: Role
  name: windows-machine-config-operator
  apiGroup: rbac.authorization.k8s.io
