apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: windows-machine-config-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
# service permissions needed for the metrics server
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
# deployment/finalizers permissions needed for the metrics server
- apiGroups:
  - apps
  resourceNames:
  - windows-machine-config-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
# TODO: pods permissions needed as we are currently watching pods
# remove as part of https://issues.redhat.com/browse/WINC-340
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
# These permissions needed for the metrics server
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - wmc.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: windows-machine-config-operator
rules:
 - apiGroups:
   - ""
   resources:
   - nodes
   verbs:
   - "*"
# The infrastructure endpoint is used within WNI
 - apiGroups:
   - "config.openshift.io"
   resources:
   - infrastructures
   verbs:
   - get
 - apiGroups:
   - certificates.k8s.io
   resources:
   - certificatesigningrequests
   - certificatesigningrequests/approval
   verbs:
   - get
   - list
   - update
